### ISSUE TITLE
Error libgdiplus is missing

### ISSUE THREAD

**Issue by noahfalk** [dotnet/performance#727] opened 2019-08-02 07:40 UTC
Repro:
1) Ubuntu 18.04 x64
2) Install .Net Core 2.2 SDK
3) git clone https://github.com/dotnet/performance
4) cd performance/src/benchmarks/micro
5) sudo apt-get install libgdiplus
6) Run dotnet run -c Release -f netcoreapp2.2 --filter *Burgers*
Expected: Burgers benchmark runs
Actual: Error message is printed:

```
libgdiplus is missing, you can install it by running 'apt-get install libgdiplus'

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> SYstem.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotGoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
    at Interop.Libdl.dlopen(String filename, Int32 flag)
    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
…
```

This error occurred both before and after running sudo apt-get install libgdiplus. Enabling LD_DEBUG shows that the actual library the code is trying to load and not finding just prior to the error message printing is 'libdl'

**Comment by billwert** [comment] 2019-08-02 18:36
Historically installing libgdiplus has fixed this for me. I wonder if the package has changed in some way.

@adamsitnik you added this error message. Do you have further context?

**Comment by adamsitnik** [comment] 2019-08-07 08:56
Anytime I was using a fresh Ubuntu VM I was always hitting the problem of missing `libgdiplus` and `sudo apt-get install libgdiplus` was always enough to solve the problem. I've never hit the missing `libdl`.

@noahfalk is there anything special about your Ubuntu 18.04 machine? Is it latest Ubuntu 18.04 or some very old version? How did you solve the problem?

Also your log contains a suprising typo:

System.DllNot**G**oundException

is it some copy-paste error?

**Comment by noahfalk** [comment] 2019-08-07 10:36
it was the latest ubuntu 18.04 downloaded ~1 week ago

> How did you solve the problem?

I did something like 'echo Burgers | dotnet run -c Release -f netcoreapp2.2'. The test with the failure wasn't one I wanted to run and doing it this way appears to avoid the issue.

> is it some copy-paste error?

I'm sure its my typo. I was reading the error from the VM UI displayed by Hyper-V and retyping it into my browser that was running on the windows host machine.

**Comment by wfurt** [comment] 2020-01-23 00:55
I have same issue on MacOS. I'm not even trying to run all tests:
```
Idle-Scenarios:micro furt$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103

# dotnet run -c release -f  netcoreapp5.0  --filter SslStreamTests

Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData.CreateTestImage(ImageFormat format) in /Users/furt/github/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 94
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData..ctor(ImageFormat format) in /Users/furt/github/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 78
   at System.Drawing.Tests.Perf_Image_Load.CreateTestCases() in /Users/furt/github/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 53
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at System.Drawing.Tests.Perf_Image_Load.ImageFormats() in /Users/furt/github/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ImmutableConfig immutableConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /Users/furt/github/performance/src/benchmarks/micro/Program.cs:line 35

```

it would be great if individual tests do not impact everything. AFAIK, corefx has detection if GDI is available or not to prevent issues like this. 

cc: @safern

**Comment by filipnavara** [comment] 2020-01-23 01:00
@wfurt A workaround is to either 1) install "mono-libgdiplus" through Homebrew or 2) apply a patch to make the error non-fatal (https://github.com/filipnavara/performance/commit/7147e390bb20d101729c16cbee8d1767d7e1ca1a).

The code tries to do the test case evaluation lazily but apparently it doesn't work as intended.

**Comment by wfurt** [comment] 2020-01-23 01:13
I end up independently with something very similar. Would it be reasonable to skip tests when external prerequisites are not met @adamsitnik ?  I can run dotnet on this machine as well as build and run all runtime tests. Or would it be sufficient to blow up when somebody attemps to run the test? We can possblly return array of failing tests rather then bomb in construcktor.

Thoughts?

**Comment by safern** [comment] 2020-01-23 01:23
That's what we do in the runtime repo, we condition the tests to not run if we can't find libgdiplus is installed in the machine:

https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/PlatformDetection.cs#L36-L57

Anyway, @noahfalk did you try installing libdl?

**Comment by noahfalk** [comment] 2020-01-23 02:57
> Anyway, @noahfalk did you try installing libdl?

I attempted to install libgdiplus with an assumption that it would also install dependencies if those were missing. At this point its been too long for me to remember if I attempted any other commands to install libdl, but I never fixed the issue - I worked around it as described above. Since then I've had no need to run those tests and I no longer have the repro environment.

**Comment by wfurt** [comment] 2020-02-10 22:41
I updated the code for OSX. Since we no longer have repro and this is pretty old, should we just close it? It does not seem actionable.

**Comment by adamsitnik** [comment] 2020-04-24 07:52
> I updated the code for OSX. Since we no longer have repro and this is pretty old, should we just close it? It does not seem actionable.

@wfurt good idea, I am going to close it

**Closed by adamsitnik** 2020-04-24 07:52 UTC

**Comment by Gnbrkm41** [comment] 2020-07-28 10:40
I hit the same kind of issue during attempts to run benchmark on my RPi 3B+ w/ Ubuntu arm64. Here is my output:
```cs
ubuntu@ubuntu:~/source/repos/performance/src/benchmarks/micro$ cro$ dotnet run -c Release -f net5.0     --filter Perf_BitArray*     --statisticalTest 3ms     --coreRun         "/home/ubuntu/before/net5.0-Linux-Release-arm64/shared/Microsoft.NETCore.App/5.0.0/corerun"         "/home/ubuntu/after/net5.0-Linux-Release-arm64/shared/Microsoft.NETCore.App/5.0.0/corerun"     --disasm
libgdiplus is missing, you can install it by running 'apt-get install libgdiplus'
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Interop.Libdl.dlopen(String fileName, Int32 flag)
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData.CreateTestImage(ImageFormat format) in /home/ubuntu/source/repos/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 98
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData..ctor(ImageFormat format) in /home/ubuntu/source/repos/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 83
   at System.Drawing.Tests.Perf_Image_Load.CreateTestCases() in /home/ubuntu/source/repos/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 53
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at System.Drawing.Tests.Perf_Image_Load.ImageFormats() in /home/ubuntu/source/repos/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ImmutableConfig immutableConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /home/ubuntu/source/repos/performance/src/benchmarks/micro/Program.cs:line 41
```

Some other similar issues such as https://github.com/dotnet/dotnet-docker/issues/618 suggested that I may be missing some other dependencies, so I tried `sudo apt-get install libgdiplus libc6-dev libx11-dev`, and now it seems to work.

**Comment by safern** [comment] 2020-07-28 18:05
It might be worth to expand this condition to all OSes. There are some windows SKUs as well that might not carry GDI+ like nano or server core.

https://github.com/dotnet/performance/pull/1173/files#diff-18cd5ab72627c912954386cf254f95a6R69
