### ISSUE TITLE
--buildTimeout doesn't seem to work

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#1231] opened 2020-03-10 04:42 UTC
Platform: OSX
Runtime: Mono --interpreter

Short description: Still get time out errors even with a very large --buildTimeout argument

I encountered this trying to run the microbenchmarks on Mono with the interpreter, although I suspect it might be possible to reproduce more easily by constructing a slow to build benchmark. None the less, I have include repro steps using mono below. 
I had to use an older hash of the microbenchmarks to get it to work with the SDK mono uses, but it doesn't look like this has been fixed. I used commit 6efd0eec96390d7c89449a3a543c1e64fafec087 from dotnet/performance.

### 2. Build mono, and patch dotnet to use it

 In the git clone root do:

 ```
./autogen.sh --with-core=only
make
cd netcore/
make patch-local-dotnet
```

a binary in <gitroot>/.dotnet/dotnet, which is dotnet with mono as the runtime. For convinience, you can point an environment variable at it like so:

```
export MONO_DOTNET=<gitroot>/.dotnet/dotnet
```

### 3. Set mono to use the interpreter:

```
$ export MONO_ENV_OPTIONS="--interpreter"
```
### 4. Run the benchmarks:
```
$MONO_DOTNET run -c Release -f netcoreapp5.0 MicroBenchmarks.csproj --filter "*" --buildTimeout 10000 --cli $MONO_DOTNET``` 

Multiple benchamrks fail with

```The configured timeout 00:02:00 was reached!```

despite the large time out specified.

**Comment by billwert** [comment] 2020-03-18 01:29
Hello!

I don't have a Mac to try this on. @adamsitnik do you?

**Comment by naricc** [comment] 2020-03-18 03:01
@billwert @adamsitnik

I can probably arrange for a shell on one, if that would be sufficient. Or it may repro on other platforms.

**Comment by adamsitnik** [comment] 2020-03-18 09:52
It looks like it's a BenchmarkDotNet bug, which respects the `buildTimeout` value only if `runtimes` value is specified in an explicit way:

https://github.com/dotnet/BenchmarkDotNet/blob/df434ee282a533b6dc4e07529ea8d90e4fa37a8c/src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs#L301-L303

@naricc the workaround it to specify the tfm using `--runtimes` option, so in your case it would be:

```cmd
$MONO_DOTNET run -c Release -f netcoreapp5.0 MicroBenchmarks.csproj --filter "*" --buildTimeout 10000 --cli $MONO_DOTNET --runtimes netcoreapp5.0 
```

**Comment by billwert** [comment] 2021-09-22 21:57
Closing this as there's a BDN issue tracking the root cause.

**Closed by billwert** 2021-09-22 21:57 UTC
