### ISSUE TITLE
Wasm runs failing due to browser wasm sdk being 9.0.0

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3292] opened 2023-08-23 18:32 UTC
All three wasm runs are failing due to the browser wasm sdk download from its build using the 9.0.0 sdk.
Error being hit in ci_setup.py in perf repo:
```
Traceback (most recent call last):
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 487, in <module>
    __main(sys.argv[1:])
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 483, in __main
    main(CiSetupArgs(**vars(args)))
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/ci_setup.py", line 411, in main
    dotnet_version = dotnet.get_dotnet_version(target_framework_moniker, args.cli) if args.dotnet_versions == [] else args.dotnet_versions[0]
  File "/mnt/vss/_work/1/s/Payload/performance/scripts/dotnet.py", line 582, in get_dotnet_version
    "Unable to determine the .NET SDK used for {}".format(framework)
RuntimeError: Unable to determine the .NET SDK used for net8.0
```
https://github.com/dotnet/performance/blob/main/scripts/dotnet.py#L581-L583
This seems to be due to a mismatch between the sdk being used in the wasm tooling (9.0) and the dotnet main framework still being used (8.0)

**Comment by LoopedBard3** [comment] 2023-08-23 20:02
FYI: @radical started after: https://github.com/dotnet/runtime/pull/90558.

**Comment by radical** [comment] 2023-08-23 20:49
Closing as duplicate of https://github.com/dotnet/runtime/pull/91011 .
Testing the fix right now.

**Closed by radical** 2023-08-23 20:49 UTC
Labels: bug
