### ISSUE TITLE
Wasm perf runs are failing: "The "ManagedToNativeGenerator" task failed unexpectedly."

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2455] opened 2022-05-26 18:16 UTC
Wasm perf runs are failing. This issue is to track an ongoing investigation here: https://github.com/dotnet/runtime/issues/69861
Full error we are seeing is:
```
/home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018: The "ManagedToNativeGenerator" task failed unexpectedly. [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018: System.IO.FileNotFoundException: Could not find assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly. [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaModule.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeHandle(BlobReader& blobReader, Byte rawTypeKind, Boolean allowTypeSpecifications) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeMethodSignature(BlobReader& blobReader) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaMethodDecoder.SpecializeMethodSig(IRoMethodBase roMethodBase) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.RoDefinitionMethod`1.ComputeMethodSig() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.RoMethod.get_ReturnType() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at SignatureMapper.MethodToSignature(MethodInfo method) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.<ProcessType>g__AddSignature|15_1(Type type, MethodInfo method) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.ProcessType(Type type) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.GenIcallTable(String runtimeIcallTableFile, String[] assemblies, String outputPath) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at ManagedToNativeGenerator.ExecuteInternal() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at ManagedToNativeGenerator.Execute() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] Build FAILED.
[2022/05/26 09:25:59][INFO] CSC : warning CS8002: Referenced assembly 'MicroBenchmarks, Version=42.42.42.42, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018: The "ManagedToNativeGenerator" task failed unexpectedly. [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018: System.IO.FileNotFoundException: Could not find assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly. [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaModule.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeHandle(BlobReader& blobReader, Byte rawTypeKind, Boolean allowTypeSpecifications) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeMethodSignature(BlobReader& blobReader) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.Ecma.EcmaMethodDecoder.SpecializeMethodSig(IRoMethodBase roMethodBase) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.RoDefinitionMethod`1.ComputeMethodSig() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at System.Reflection.TypeLoading.RoMethod.get_ReturnType() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at SignatureMapper.MethodToSignature(MethodInfo method) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.<ProcessType>g__AddSignature|15_1(Type type, MethodInfo method) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.ProcessType(Type type) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at IcallTableGenerator.GenIcallTable(String runtimeIcallTableFile, String[] assemblies, String outputPath) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at ManagedToNativeGenerator.ExecuteInternal() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at ManagedToNativeGenerator.Execute() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
[2022/05/26 09:25:59][INFO] /home/helixbot/work/B6D809AE/p/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(286,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/helixbot/work/B6D809AE/w/9D2A08CC/e/performance/artifacts/bin/for-running/MicroBenchmarks/555921cc-24d5-44bf-8be5-2f734c4aa2f8/BenchmarkDotNet.Autogenerated.csproj]
```

**Comment by radical** [comment] 2022-05-26 18:40
Closing as dupe of https://github.com/dotnet/runtime/issues/69861 .

**Comment by radical** [comment] 2022-05-26 18:40
Sorry, I thought this was on dotnet/runtime!

**Comment by radical** [comment] 2022-05-28 07:29
Fixed by https://github.com/dotnet/runtime/pull/69886 .

**Closed by radical** 2022-05-28 07:29 UTC
Labels: pipeline blocker, WRI
