### ISSUE TITLE
Deprecation warning for dhcrypto and Python 3.6

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#3064] opened 2023-06-05 10:28 UTC
```text
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.utils import int_from_bytes
```

In `dotnet-runtime-perf` and related.

**Comment by LoopedBard3** [comment] 2024-02-20 20:38
Duplicate of: https://github.com/dotnet/performance/issues/2403. Issue is gone so closing both.

**Closed by LoopedBard3** 2024-02-20 20:38 UTC
