### ISSUE TITLE
MicroBenchmarks.dll fails with "The specified network password is not correct."

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/performance#2454] opened 2022-05-25 19:41 UTC
We are seeing failures in our superpmi collection as soon as we start executing MicroBenchmarks. Wondering if perf lab is also seeing these failures and what is the fix? This is blocking our ability to do superpmi collection on benchmarks.

```
[18:22:58] C:\h\w\97FE0875\w\9B61093D\u\performance>C:\h\w\97FE0875\w\9B61093D\u\performance\tools\dotnet\x64\dotnet C:\h\w\97FE0875\w\9B61093D\u\performance\artifacts\MicroBenchmarks.dll  --filter "*" --corerun C:\h\w\97FE0875\p\superpmi\CoreRun.exe --partition-count 30 --partition-index 11 --envVars COMPlus_JitName:superpmi-shim-collector.dll  COMPlus_ZapDisable:1  COMPlus_ReadyToRun:0 --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart 
[18:22:58] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Security.Tests.SslStreamTests' threw an exception.
[18:22:58]  ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
[18:22:58]    at System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
[18:22:58]    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[18:22:58]    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
[18:22:58]    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\h\w\97FE0875\w\9B61093D\u\performance\src\benchmarks\micro\libraries\System.Net.Http\Configuration.Certificates.cs:line 27
[18:22:58]    at System.Net.Security.Tests.SslStreamTests..cctor() in C:\h\w\97FE0875\w\9B61093D\u\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.cs:line 24
[18:22:58]    --- End of inner exception stack trace ---
[18:22:58]    at System.Net.Security.Tests.SslStreamTests.TlsProtocols()+MoveNext() in C:\h\w\97FE0875\w\9B61093D\u\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.Protocols.cs:line 22
[18:22:58]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
[18:22:58]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[18:22:58]    at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
[18:22:58]    at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
[18:22:58]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
[18:22:58]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[18:22:58]    at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
[18:22:58]    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
[18:22:58]    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
[18:22:58]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
[18:22:58]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[18:22:58]    at MicroBenchmarks.Program.Main(String[] args) in C:\h\w\97FE0875\w\9B61093D\u\performance\src\benchmarks\micro\Program.cs:line 47
```

I am not sure if https://github.com/dotnet/performance/pull/1750 is related but we started seeing the failures around that time.

**Comment by kunalspathak** [comment] 2022-05-25 19:41
@DrewScoggins @[wfurt](https://github.com/wfurt)

**Comment by kunalspathak** [comment] 2022-05-25 19:41
@BruceForstall FYI.

**Comment by BruceForstall** [comment] 2022-05-25 19:48
e.g., here's a link to a failed run.

https://dev.azure.com/dnceng/internal/_build/results?buildId=1783706&view=logs&j=780b3331-d7b2-5848-543a-ef5d1bbff1c9&t=efe49bc7-a53a-5503-4fec-d1c38bd80ad8

It's in the "internal" pipelines group, so you can't just click to find the console log, you need some Kusto magic, but I wanted to drop a link here anyway.

**Comment by BruceForstall** [comment] 2022-05-26 06:07
@DrewScoggins @wfurt Note in particular:
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
```

Is this being seen in the normal performance runs? Was anything done to ensure this passes in normal perf runs? (We might be running our superpmi collection runs on a different set of Helix machines, for instance)

**Comment by wfurt** [comment] 2022-05-26 07:27
What platform this is running on? I did run on my Linux box and I don't see any failure. 
From the stack above, it looks like it is failing to load ECDH key. 
I'm wondering if the error is lame and the root case is in ECDH support...
cc: @rzikm 

https://github.com/dotnet/performance/pull/1750 is more than year old. It would be surprising if that is the culprit.

**Comment by kunalspathak** [comment] 2022-05-26 13:09
> What platform this is running on?

We are seeing failures on windows. Linux runs are fine.

> https://github.com/dotnet/performance/pull/1750 is more than year old.

That's true...I misread the year :)

**Comment by wfurt** [comment] 2022-05-26 13:42
I just did run on my Win11 and everything works ok. So I'm reasonably confident the password is not wrong. 
cc: @bartonjs for any more thoughts as it seems to fail load certificate from PFX.

**Comment by kunalspathak** [comment] 2022-05-26 16:48
We didn't change anything in the way it is run.

**Comment by BruceForstall** [comment] 2022-05-26 18:08
> We didn't change anything in the way it is run.

To expand on this, our pipeline has been running the same way for a long time, and we haven't recently changed anything about how we run the pipeline. Changes we'd worry about would be (1) changes to the dotnet/performance repo, (2) changes to Helix/AzDO infrastructure, (3) changes to the daily dotnet SDK build (i.e., the product).

**Comment by wfurt** [comment] 2022-05-26 18:21
That would leave #2405 as suspect IMHO. We can try to revert it and give it try. However, it did pass all the CI tests. 
It is not clear to me if `superpmi` was passing at that time or not. And why that would be any different from the PR tests. 
cc: @rzikm.

**Comment by BruceForstall** [comment] 2022-05-26 18:46
I'm not sure if this matters, but note that the superpmi collect pipeline runs in the "internal" (not "public") AzDO TeamProject, which has a separate set of Helix machines.

**Comment by MattGal** [comment] 2022-05-26 21:52
> I assume performance CI does _not_ run from Helix. Maybe @MattGal may have some insight about [#2454 (comment)](https://github.com/dotnet/performance/issues/2454#issuecomment-1138736129).

- To @JSBarton's point, I can confirm that anything running on windows.10.amd64.x86.rt is running in an interactive user session with a local, randomly generated account name "runner", UAC disabled.
- The image used on this queue has not changed since 5/11/2022 (though it is rolling out changes today).  While this happened around the same time, there's runs using the image rolled out on 5/11 (`WorkItems| where JobName == "96330f1e-bad9-4c6f-a2bd-56288b632df2"`) that do not show this problem.
- I suggest investigating to see if you can get a repro using a VM from https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/d60c2e3b-00e6-48f3-a069-542c17981e1f/resourceGroups/helix-repro-vms/providers/Microsoft.DevTestLab/labs/helix-repro-vms/overview.  If you find we have something wrong with the machines in question, file an issue in dotnet/arcade.
- In the short term to differentiate if this is something in helix or something in the work items themselves, I'd suggest rerunning the last good commit (dc7728f1f2ef1d1a78286e9ae6c5d7dfe25e673c) and see if it repros; if it doesn't the problem is definitely in the 50+ commits between the last good and first bad runs.

**Comment by kunalspathak** [comment] 2022-05-26 22:19
> I'd suggest rerunning the last good commit (dc7728f1f2ef1d1a78286e9ae6c5d7dfe25e673c)

That's a good point. Started the run.

**Comment by kunalspathak** [comment] 2022-05-27 12:53
And the run failed with same errors. So, it seems that something has changed on helix side.

**Comment by MattGal** [comment] 2022-05-31 16:19
> And the run failed with same errors. So, it seems that something has changed on helix side.

Can you please check this out using the devtest lab linked and let me know what you suspect the problem is?  Nothing interesting has changed here for the images other than usual windows updating so we could very much use the input.  Ping me if you have any issues with this approach and I'll help unblock you.

**Comment by kunalspathak** [comment] 2022-06-02 23:05
I have started on this. Creating the VM.

**Comment by kunalspathak** [comment] 2022-06-03 23:24
@MattGal - I am able to reproduce the issue on the VM.

```
-434b-a665-1d8cc28c4698\superpmi\CoreRun.exe --partition-count 30 --partition-index 0 --envVars COMPlus_JitName:superpmi-shim-collector.dll  COMPlus_ZapDisable:1  COMPlus_ReadyToRun:0 --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart
[23:23:06] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Security.Tests.SslStreamTests' threw an exception.
[23:23:06]  ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
[23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
[23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[23:23:06]    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
[23:23:06]    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Http\Configuration.Certificates.cs:line 27
[23:23:06]    at System.Net.Security.Tests.SslStreamTests..cctor() in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.cs:line 24
[23:23:06]    --- End of inner exception stack trace ---
[23:23:06]    at System.Net.Security.Tests.SslStreamTests.TlsProtocols()+MoveNext() in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.Protocols.cs:line 22
[23:23:06]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
[23:23:06]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
[23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
[23:23:06]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
[23:23:06]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
[23:23:06]    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
[23:23:06]    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
[23:23:06]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
[23:23:06]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[23:23:06]    at MicroBenchmarks.Program.Main(String[] args) in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\Program.cs:line 47
[23:23:06] Done. Elapsed time: 1:09:59.516954
[23:23:06] No .mc files generated.
[23:23:06] Finish time: 23:23:06
[23:23:06] Elapsed time: 1:09:59.516954
```

**Comment by MattGal** [comment] 2022-06-06 16:25
> @MattGal - I am able to reproduce the issue on the VM.
> 
> ```
> -434b-a665-1d8cc28c4698\superpmi\CoreRun.exe --partition-count 30 --partition-index 0 --envVars COMPlus_JitName:superpmi-shim-collector.dll  COMPlus_ZapDisable:1  COMPlus_ReadyToRun:0 --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart
> [23:23:06] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Security.Tests.SslStreamTests' threw an exception.
> [23:23:06]  ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
> [23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
> [23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
> [23:23:06]    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
> [23:23:06]    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Http\Configuration.Certificates.cs:line 27
> [23:23:06]    at System.Net.Security.Tests.SslStreamTests..cctor() in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.cs:line 24
> [23:23:06]    --- End of inner exception stack trace ---
> [23:23:06]    at System.Net.Security.Tests.SslStreamTests.TlsProtocols()+MoveNext() in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.Protocols.cs:line 22
> [23:23:06]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
> [23:23:06]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
> [23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
> [23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
> [23:23:06]    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
> [23:23:06]    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
> [23:23:06]    at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
> [23:23:06]    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
> [23:23:06]    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
> [23:23:06]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
> [23:23:06]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
> [23:23:06]    at MicroBenchmarks.Program.Main(String[] args) in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\Program.cs:line 47
> [23:23:06] Done. Elapsed time: 1:09:59.516954
> [23:23:06] No .mc files generated.
> [23:23:06] Finish time: 23:23:06
> [23:23:06] Elapsed time: 1:09:59.516954
> ```

Discussed with @kunalspathak , this is great progress but we also need to know what you'd like changed about the machine (some sort of root cause, ideally) before the dnceng team can proceed.

**Comment by kunalspathak** [comment] 2022-06-06 22:51
@GrabYourPitchforks , @bartonjs - We tried to debug this and we don't understand which part of certificate password is wrong. This app is working fine in perf lab, so pretty sure the helix VMs have outdated password? Can you help us find out the discrepancy? If you want, I can give you the access to the machine where this is 100% consistently reproducible.

**Comment by MattGal** [comment] 2022-06-06 22:53
> pretty sure the helix VMs have outdated password

@kunalspathak can you clarify here what you mean, given you said you reproduced the problem on a machine as a user you created the password of yourself?

**Comment by kunalspathak** [comment] 2022-06-06 22:57
> That would leave https://github.com/dotnet/performance/pull/2405 as suspect IMHO. We can try to revert it and give it try. 

Not sure why #2405 didn't updated all the pfx files. 

However, it did pass all the CI tests. It is not clear to me if superpmi was passing at that time or not. And why that would be any different from the PR tests.

> That's because superpmi is not run as part of the CI. It is a separate tool that codegen team uses.


@rzikm - any thoughts?

**Comment by kunalspathak** [comment] 2022-06-06 22:57
> @kunalspathak can you clarify here what you mean, given you said you reproduced the problem on a machine as a user you created the password of yourself?

I will coordinate with you offline.

**Comment by rzikm** [comment] 2022-06-07 07:07
> Not sure why #2405 didn't updated all the pfx files.

The test*eku.contoso.com.pfx certificates were not expired and will be valid for years more.

I don't know anything about superpmi, so I'm afraid I can't help you there. sorry.

**Comment by BruceForstall** [comment] 2022-06-07 17:14
> I don't know anything about superpmi, so I'm afraid I can't help you there. sorry.

@rzikm This issue has nothing to do with superpmi. It is related to a "The specified network password is not correct." message when loading a certificate:

```
[23:23:06] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Security.Tests.SslStreamTests' threw an exception.
[23:23:06]  ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The specified network password is not correct.
[23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
[23:23:06]    at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[23:23:06]    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
[23:23:06]    at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Http\Configuration.Certificates.cs:line 27
[23:23:06]    at System.Net.Security.Tests.SslStreamTests..cctor() in C:\Users\kpathak\helix\workitems\Partition0\Partition0\performance\src\benchmarks\micro\libraries\System.Net.Security\SslStreamTests.cs:line 24
```

@kunalspathak mitigated it with https://github.com/dotnet/performance/pull/2469

**Comment by LoopedBard3** [comment] 2022-10-12 21:30
This appears to be fixed and merged so I will close it, please reopen it if something else pops up for this.

**Closed by LoopedBard3** 2022-10-12 21:30 UTC
